package com.ctriposs.blacksmith.stressors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.ctriposs.blacksmith.config.Stressor;
import com.ctriposs.blacksmith.features.KeyGeneratorAware;

/**
 * Produces a key generator which is retrieved from KeyGenerator-aware cache wrapper. This key generator
 * is then used to generate keys instead of the default key generator.
 */
@Stressor(doc = "Executes put and get operations with keys generated by cache-specific key generator.")
public class CacheSpecificKeyGenStressor extends StressTestStressor {

   private static final Logger log = LoggerFactory.getLogger(CacheSpecificKeyGenStressor.class);

   @Override
   public KeyGenerator getKeyGenerator() {
      synchronized(this) {
         if (keyGenerator == null) {
            if (cacheWrapper instanceof KeyGeneratorAware) {
               keyGenerator = ((KeyGeneratorAware)cacheWrapper).getKeyGenerator(getNumThreads() * getNumEntries());
            } else {
               throw new RuntimeException("Cache wrapper is not KeyGeneratorAware");
            }
         }
      }
      return keyGenerator;
   }

}
